### ISSUE TITLE
Vimeo fullscreen issues in Safari

### ISSUE THREAD

**Issue by vishaldrana** [sampotts/plyr#1266]
Hello,
Issue: i was able to reproduce issue that i am facing on plyr's demo page. full screen on "https://plyr.io/#vimeo" is not taking full screen. It takes width of half screen. Attached is the screenshot.
![image-1](https://user-images.githubusercontent.com/7623380/48750173-e4cad300-ec4b-11e8-9f71-63330231c81e.jpg)

Appreciate It.

**Comment by sampotts** [comment]
It looks like this is a Safari-wide issue. It also does it on desktop. I'm looking into it now.

**Comment by chrisschwartze** [comment]
Can also confirm this is happening on Chrome with iOS.

**Comment by Tigrecito** [comment]
any news here? 

on desktop safari a fullscreen view is opened - but the video is displayed with large black borders around (so the video it self isn´t in fullscreen -> looks like the size is fixed to original size of video)

**Comment by Ninos** [comment]
Any news about finalizing the other feature for releasig new stable version with fixed Safari bug?

**Comment by sampotts** [comment]
This is now fixed in v3.5.0 👍

**Comment by vishaldrana** [comment]
Thank you..

**Comment by brandonjp** [comment]
I'm still seeing this (or similar) issue on the Plyr demo page in Safari Version 12.0.1 (14606.2.104.1.1)

Also happening on my local files using v3.5.0 (and still only in Safari)

![cleanshot 2019-02-18 at 14 29 36](https://user-images.githubusercontent.com/199599/52975097-b3b48880-3389-11e9-8e43-084412d1b475.gif)

**Comment by sampotts** [comment]
Weird. It looks fine for me in Version 12.0.3 (14606.4.5). Perhaps there was a bug in 12.0.1?

**Comment by brandonjp** [comment]
@sampotts How the heck do you have Safari 12.0.3 ?  I can't seem to even find a way to upgrade!
I'm even still having this issue in Safari Tech Preview 76 (Safari 12.2, WebKit 14608.1.6.2)
Grrrr.  Dangit Safari!

**Comment by Tigrecito** [comment]
> @sampotts How the heck do you have Safari 12.0.3 ? I can't seem to even find a way to upgrade!
> I'm even still having this issue in Safari Tech Preview 76 (Safari 12.2, WebKit 14608.1.6.2)
> Grrrr. Dangit Safari!

I can confirm, that everything is working fine with current stable safari version (12.0.3) .. can´t tell anything about tech previews etc.. but with current existing version everything runs like expected !

**Comment by sampotts** [comment]
> I'm even still having this issue in Safari Tech Preview 76 (Safari 12.2, WebKit 14608.1.6.2)
Grrrr. Dangit Safari!

I've just tested `Release 76 (Safari 12.2, WebKit 14608.1.6.2)` of Safari Tech Preview and it also seemed ok. In Safari Tech Preview there seems to be issues with hover interaction but that also effects loads of other sites and isn't isolate to Plyr. YouTube does the same. I presume this is a bug with Safari Tech Preview. However, the fullscreen works fine for me on https://plyr.io. I tried to use Safari and Safari Tech Preview for a while but they are quite buggy.

**Comment by Leenert** [comment]
This issue persists with the current version of Safari (Version 12.1.1 (14607.2.6.1.1)). Vimeo videos are either displayed with huge borders or just in the upper left quarter of the screen. Vimeo example on [](https://plyr.io) does not work as well.

Any updates on this?
