### ISSUE TITLE
Player inherits aspect ratio of screen when exiting fullscreen

### ISSUE THREAD

**Issue by sandeepthefifth** [sampotts/plyr#2087]
### Expected behaviour
Play video (YouTube), enter fullscreen, exit fullscreen, player retains original aspect ratio.

### Actual behaviour
Play video (YouTube), enter fullscreen, exit fullscreen, player _inherits_ aspect ratio of screen.

### Steps to reproduce
Play video (YouTube) and enter fullscreen on any device. Exit fullscreen while video is playing. Most obvious on mobile devices. Will also occur on laptop screens (16:10), but obviously not 16:9 external monitors.
Safari and FF behaviour slightly different - black bars appear either side of a 16:9 video (when reproducing on a 16:10 screen), rather than on top like Chrome.

### Environment

- Browser: Android/desktop Chrome, FF, Safari
- Version: Chrome 88.0.4324.96, FF 85.0, Safari 14.0.2
- Operating System: Mac 10.15.7, Android Oxygen OS 10.5.9

### Link to where the bug is happening
[https://plyr.io/#youtube](https://plyr.io/#youtube)

**Comment by sampotts** [comment]
I'm unable to replicate this. Can you try again? I've just published a new version which _may_ contain a fix.

**Comment by sandeepthefifth** [comment]
Afraid it's still happening on all devices I previously tested, on [https://plyr.io/#youtube](https://plyr.io/#youtube). Additionally, also on iOS Simulator (14.3) (don't have an iOS device to hand).

Screenshot from Android device attached.
![Screenshot_20210201-142632](https://user-images.githubusercontent.com/400622/106471509-9a834480-6499-11eb-8c7b-2429ba93a0d7.jpg)
