### ISSUE TITLE
Vimeo videos not playing with chrome desktop Version 89.0

### ISSUE THREAD

**Issue by alexvibealex** [sampotts/plyr#2138]
Hi, 
getting a strange issue with plyr.js with vimeo videos .Videos are just start playing and then paused . 
Here is the video of the issue : http://somup.com/creIh7bjgh

html : 
`<div  id="'item_1" data-plyr-provider="vimeo" data-plyr-embed-id="502425852"></div>
`

script : 
`let config = {};
config['listeners']={
		seek:  (e) => {
			  var currentTime = plyr.currentTime;
		   var newTime = _getTargetTime(plyr, e);
			if (newTime > currentTime) {
			    e.preventDefault();
			    
			    return false;
			  }
		}
};
	
let pplayer = new Plyr(document.querySelector('#item_1'),config);`

### Environment

- Browser:Chrome
- Version:89.0
- Operating System:MacOS
- Version:High Siera

Errors in console : 
 Unrecognized feature: 'autoplay,fullscreen,picture-in-picture'.  ------  plyr.js?ver=2009:formatted:3414

 Uncaught TypeError: this.enter is not a function ----  plyr.js?ver=2009:formatted:2547

### Update 

this is happening with your own demo : https://codepen.io/pen?template=bKeXNq

**Comment by jeankhouri** [comment]
Having the same issue.

I can only replicate it on chrome running on macOS.

plyr.polyfilled.min.js:3 Unrecognized feature: 'autoplay,fullscreen,picture-in-picture'.

Browser: Chrome
Version: 89.0
Operating System: macOS
Version: Big Sur 11.1

**Comment by cfabrice** [comment]
Same here !

**Comment by alexvibealex** [comment]
Hi please anyone with any solution here? Need a quick fix urgently

**Comment by imransiddiq** [comment]
@alexvibealex @cfabrice @jeankhouri Upgrade to the latest version of Plyr **3.6.4** (https://cdnjs.cloudflare.com/ajax/libs/plyr/3.6.4/plyr.min.js) Your issue will be resolved.

**Comment by veselinn** [comment]
@imransiddiq Thank you for the tip! Unfortunately even on 3.6.4 the videos still don't play.

**Comment by cfabrice** [comment]
Hello, 
I use vue-plyr (with plyr 3.6.4) - not sure if it is vue-plyr or plyr but as mentioned just above, a user found that interacting with the video like muting it, makes it playable... without such interaction, it is not responding to play.

**Comment by tomferrall** [comment]
Just a quick question for fellow Vimeo users, is everything working correctly regarding being able to access the controls on mobile?

Discussed here:

#2018

**Comment by fredsvanelli** [comment]
Plyr 3.6.4 is available only on NPM. **Not** on GITHUB

- https://www.npmjs.com/package/plyr/v/3.6.4
- https://github.com/sampotts/plyr/tags

And it was published in January 2021

**Comment by sampotts** [comment]
This is fixed in 3.6.4. Sorry, the release on GitHub but is there now. I'm going to add lerna to handle it all eventually.

**Comment by tomferrall** [comment]
I believe I am using 3.6.4, also I am still just referring to this issue #2018 
Could you confirm whether https://plyr.io/#vimeo is using the latest version?

As I still can't use the controls on mobile after playing has started.

**Comment by alexvibealex** [comment]
Yes, we are getting the same issue on chrome on android.
After pausing the video the controls are not shown.

**Comment by daniel-easytutor** [comment]
Was the original issue with playing vimeo videos fixed? I'm using 3.6.4 and the video does not respond to play unless muted and if I unmute once the video is playing, it stops playing again.

**Comment by alexvibealex** [comment]
Yes that issue is fixed I confirm but with version 3.6.4 a new issue appear as stated in #2018  after playing the video

**Comment by daniel-easytutor** [comment]
@alexvibealex  is any changes on the client code side required? since on the latest version and it's not working in my case

**Comment by yurenery** [comment]
> Yes that issue is fixed I confirm but with version 3.6.4 a new issue appear as stated in #2018 after playing the video

Yes, same problem here. Once the video starts, the controls no longer appear on mobile.

**Comment by AndriyLenginDev** [comment]
Hello everyone.
@cfabrice I am using the latest vue-plyr and plyr (v3.6.4) and experiencing the same problem. Got this console error logs
`Uncaught (in promise) NotAllowedError: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD`
The problem can be reproduced in the Chrome browser only (v89.0.4389.90 for Windows, v89.0.4389.90 for Mac, mobile devices). After some research found that video can play only when muted or when it was clicked directly on the iframe (need to remove plyr overlays).

@sampotts Also after the template checking I see that "allow" attribute is `allow="autoplay,fullscreen,picture-in-picture"` with the comma separator "," but in the source files I see that it needs to be  `iframe.setAttribute('allow', ['autoplay', 'fullscreen', 'picture-in-picture'].join('; '));` -  with the semicolon separator ";". Maybe this is the problem?

Thanks for any information and help

**Comment by darkylmnx** [comment]
the bug is still happening on 3.6.4 on Chrome windows!

**Comment by sampotts** [comment]
@darkylmnx Are you able to provide a link where I can reproduce the issue? I'm unable to replicate it on Chrome 90.  

Please keep this issue about the original issue of playback. The controls issue is #2018.

**Comment by darkylmnx** [comment]
> @darkylmnx Are you able to provide a link where I can reproduce the issue? I'm unable to replicate it on Chrome 90.

@sampotts as you can see on this video, on Chrome 89 on Windows, it doesn't work.
Sometimes when I'm not on incognito mode, it works, just as if previous user-interaction makes Chrome fix the thing.
But it's pretty random.

On Firefox, everything is fine.

Here's a demo video of the issue: https://vimeo.com/529880040/999e116da7

Here's my Chrome version
![image](https://user-images.githubusercontent.com/1426357/112741792-e37ee300-8f88-11eb-9229-db842661fe0f.png)

Here's the CodeSandbox: https://codesandbox.io/s/broken-shadow-v8lls?file=/src/App.vue

I have a Codpen version too: https://codepen.io/darkylmnx/pen/RwKNJbW

Here's a message in the console: `plyr@3:3 Allow attribute will take precedence over 'allowfullscreen'.`

And with this url as source: https://player.vimeo.com/video/529880040
I get:
```
vue-plyr.esm.js:4853 Unrecognized feature: 'autoplay,fullscreen,picture-in-picture'.
vue-plyr.esm.js:3149 GET https://vimeo.com/api/v2/video/529880040.json 404 (Not Found)
```

**Comment by utsw-philp** [comment]
Has anyone else experienced the following after upgrading to 3.6.4:
1. Vimeo plays on Chrome as expected.
2. Now breaks the container on Firefox v88 and Safari v14.1 (MacOS v10.15.7)

Is there CSS updates that need to be implemented with 3.6.4 change?

<img width="2505" alt="Screen Shot 2021-04-27 at 2 54 46 PM" src="https://user-images.githubusercontent.com/54282015/116304827-98fbac80-a768-11eb-8af5-1cbe66b11f2d.png">

**Comment by 80sguy** [comment]
I'm still getting this issue and am using Mac Chrome 91,  `"vue-plyr":"^7.0.0",` and `"plyr": "^3.6.4",`. Has anyone been able to find a fix? The video will play if you mute it, but as soon as you unmute it you can no longer play the video :(

**Comment by daun** [comment]
Same thing here on Mac Chrome 91 with `plyr` resolving to the latest version `3.6.8`. Console log says `Unrecognized feature: 'autoplay,fullscreen,picture-in-picture'` and playing the video only works when pausing it manually beforehand.

**Comment by sampotts** [comment]
I'm unable to replicate this on Chrome `Version 91.0.4472.77 (Official Build) beta (arm64)`. Vimeo plays back fine, without a console error relating to the `allow` attribute. Also we no longer use the old syntax, this was fixed a while back to use the new semi-colon separated list: 
https://github.com/sampotts/plyr/blob/32444c9851414a1f1947add04e4c3be47b964b0e/src/js/plugins/vimeo.js#L109

<img width="2031" alt="CleanShot 2021-05-26 at 23 14 24@2x" src="https://user-images.githubusercontent.com/719092/119665838-1efa3880-be78-11eb-844a-786d5d0651fa.png">

**Comment by 80sguy** [comment]
I updated to plyr 3.6.7 and all working ok now! Thanks for your help

**Comment by daun** [comment]
Forking `vue-plyr` and updating to `v3.6.8` solves the issue for me as well.
