### ISSUE TITLE
npm compile error with math.div function

### ISSUE THREAD

**Issue by nockschii** [sampotts/plyr#2351]
So there is a weird bug when building my npm scripts
Followng error is showing:

![image](https://user-images.githubusercontent.com/22520261/137495741-1e0cd1c1-4cd8-4b54-8979-36699d91516a.png)

Can you help us with this problem?

**Comment by stevepepple** [comment]
I just started experience the same error with node-sass in Gatsby. 

1:10:34 PM: failed Building production JavaScript and CSS bundles - 328.253s
1:10:34 PM: error Generating JavaScript bundles failed
1:10:34 PM: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
1:10:34 PM: SassError: Invalid CSS after "...-padding: (math": expected expression (e.g. 1px, bold), was ".div(100, 16) * 9);"
1:10:34 PM:         on line 27 of node_modules/plyr/src/sass/types/video.scss
1:10:34 PM:         from line 1119 of node_modules/plyr/src/sass/plyr.scss
1:10:34 PM: >> $embed-padding: (math.div(100, 16) * 9);
1:10:34 PM:    ---------------------^

**Comment by merlijn** [comment]
I experienced the same thing. My project was using [node-sass](https://github.com/sass/node-sass). I now switched to [dart-sass](https://github.com/sass/dart-sass) which is recommended anyway since node sass is deprecated.

This solved the issue for me.

**Comment by stevepepple** [comment]
> I experienced the same thing. My project was using [node-sass](https://github.com/sass/node-sass). I now switched to [dart-sass](https://github.com/sass/dart-sass) which is recommended anyway since node sass is deprecated.
> 
> This solved the issue for me.

Thanks for the suggestion. In my case, it looks like changing the Gatsby framework plugin to dart-sass or adding a package resolution should do the trick.

**Comment by omarceleza** [comment]
Hi, same issue here, its only change math.div function, can we upgrade the source code?

`SassError: Undefined function.
   ╷
27 │ $embed-padding: (math.div(100, 16) * 9);
   │                  ^^^^^^^^^^^^^^^^^
   ╵
  node_modules/plyr/src/sass/types/video.scss 27:18  @import
  node_modules/plyr/src/sass/plyr.scss 44:9          @import`

**Comment by JayBox325** [comment]
Getting this issue randomly today.

```
[14:19:18] gulp-notify: [❌  error] Error in plugin "gulp-sass"
Message:
    node_modules/plyr/src/sass/types/video.scss
Error: Invalid CSS after "...-padding: (math": expected expression (e.g. 1px, bold), was ".div(100, 16) * 9);"
        on line 27 of node_modules/plyr/src/sass/types/video.scss
        from line 44 of node_modules/plyr/src/sass/plyr.scss
        from line 6 of _src/styles/base/imports.scss
        from line 29 of _src/styles/styles.scss
>> $embed-padding: (math.div(100, 16) * 9);

   ---------------------^

Details:
    status: 1
    file: /Users/jaycollett/Sites/bwu/leiter-shop/_project/_frontend/node_modules/plyr/src/sass/types/video.scss
    line: 27
    column: 22
    formatted: Error: Invalid CSS after "...-padding: (math": expected expression (e.g. 1px, bold), was ".div(100, 16) * 9);"
        on line 27 of node_modules/plyr/src/sass/types/video.scss
        from line 44 of node_modules/plyr/src/sass/plyr.scss
        from line 6 of _src/styles/base/imports.scss
        from line 29 of _src/styles/styles.scss
>> $embed-padding: (math.div(100, 16) * 9);

   ---------------------^

    messageFormatted: node_modules/plyr/src/sass/types/video.scss
Error: Invalid CSS after "...-padding: (math": expected expression (e.g. 1px, bold), was ".div(100, 16) * 9);"
        on line 27 of node_modules/plyr/src/sass/types/video.scss
        from line 44 of node_modules/plyr/src/sass/plyr.scss
        from line 6 of _src/styles/base/imports.scss
        from line 29 of _src/styles/styles.scss
>> $embed-padding: (math.div(100, 16) * 9);

   ---------------------^

    messageOriginal: Invalid CSS after "...-padding: (math": expected expression (e.g. 1px, bold), was ".div(100, 16) * 9);"
    relativePath: node_modules/plyr/src/sass/types/video.scss
    ```

**Comment by matthieua** [comment]
Any updates on this? I can't upgrade plyr.js to 3.6.9 and therefore we don't benefit from the support for upcoming private Vimeo videos changes coming early next year. I've switched from `node-sass` to `dart-sass` and still getting a compilation error because of the usage of `math.div`

![image](https://user-images.githubusercontent.com/234575/146011137-03ac972f-1c27-4355-b122-0dba0cf7950c.png)

**Comment by merlijn** [comment]
Same here.

I would be willing to do a PR but to be honest I am a little out my depth with this. I might spend some time on it over the weekend anyway if I have time.

**Comment by sampotts** [comment]
This should now be fully resolved in v3.6.10 but please report back if not 👍🏼

**Comment by matthieua** [comment]
@sampotts I've just upgraded but I'm still having the same issue :(
![image](https://user-images.githubusercontent.com/234575/146352811-54353d70-c24f-4771-9646-98f95b3e2497.png)

**Comment by sampotts** [comment]
Ah, damn. How can I replicate this? It builds fine using the standard `sass` package.

**Comment by matthieua** [comment]
I'm not sure. Is there a chance you remove the `math.div` on line 27:22 of node_modules/plyr/src/sass/types/video.scss

**Comment by sampotts** [comment]
`math.div(x, y)` is the new SASS syntax to replace `x / y` . There were issues created to remove the deprecated syntax and move to use the new format.

**Comment by adeeb1** [comment]
Still getting this error as well:

```
ERROR in ./node_modules/plyr/dist/plyr.css (./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/postcss-loader/src??ref--5-2!./node_modules/plyr/dist/plyr.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
ParserError: Syntax Error at line: 1, column 51
    at /home/user/project/node_modules/plyr/dist/plyr.css:1:2215
    at Parser.error (/home/user/project/node_modules/postcss-values-parser/lib/parser.js:127:11)
    at Parser.operator (/home/user/project/node_modules/postcss-values-parser/lib/parser.js:162:20)
    at Parser.parseTokens (/home/user/project/node_modules/postcss-values-parser/lib/parser.js:245:14)
    at Parser.loop (/home/user/project/node_modules/postcss-values-parser/lib/parser.js:132:12)
    at Parser.parse (/home/user/project/node_modules/postcss-values-parser/lib/parser.js:51:17)
    at parse (/home/user/project/node_modules/postcss-custom-properties/index.cjs.js:47:30)
    at /home/user/project/node_modules/postcss-custom-properties/index.cjs.js:333:24
    at /home/user/project/node_modules/postcss/lib/container.js:194:18
    at /home/user/project/node_modules/postcss/lib/container.js:139:18
    at Rule.each (/home/user/project/node_modules/postcss/lib/container.js:105:16)
ℹ ｢wdm｣: Failed to compile.
```

Should I be adding a specific package to my project so that this would work?

**Comment by sampotts** [comment]
Have you tried the latest build?

**Comment by adeeb1** [comment]
> 

Yes, same error. I am not sure why though. I'll keep looking into it to make sure nothing is cached.

**Comment by VicFleur** [comment]
The following files seems to be preventing the production builds:
- `sass/components/menus.scss`
- `sass/components/progress`
- `sass/components/sliders`

In particular, every `calc()` that ends with a `* -1` multiplication throws an error, but only in production.

If you move the multiplication at the front (ie. `calc(-1 * ( ... ))` ) then it works

**Comment by adeeb1** [comment]
For those still experiencing errors with this, I finally found my fix! I am running Rails 6 with [webpacker](https://github.com/rails/webpacker), which includes **postcss**. I found [this issue](https://github.com/fullcalendar/fullcalendar/issues/5503#issue-640007498) that suggests changing the `postcss.config.js` file's `stage` value from the default (3) to 4 to enable more CSS features. Once I enabled this, everything started working! For reference, here's my `postcss.config.js file`:

```
module.exports = {
  plugins: [
    require('postcss-import'),
    require('postcss-flexbugs-fixes'),
    require('postcss-preset-env')({
      autoprefixer: {
        flexbox: 'no-2009'
      },
      // I changed this from 3 to 4
      stage: 4
    })
  ]
}

```

**Comment by pxcz** [comment]
fix for Nuxt.js (node-sass@6, sass-loader@10, webpack@4) based on @adeeb1 solution - nuxt.config.js:
`
	build: {
		postcss: {
			preset: {
				stage: 4,
			},
		},
	}
`

**Comment by mrleblanc101** [comment]
@pxcz Did you have to transpile plyr too ?
```
build: {
    // extractCSS: true,
    /*
     ** You can extend webpack config here
     */
    postcss: {
        preset: {
            stage: 4,
        },
    },
    transpile: ['plyr'],
},
```
Otherwise I get this error:
> ERROR in ./node_modules/plyr/dist/plyr.min.js 1:24985
Module parse failed: Unexpected token (1:24985)
