### ISSUE TITLE
ESM entry uses extensionless relative imports; fails under strict ESM resolution (Rspack/Webpack fullySpecified)

### ISSUE THREAD

**Issue by AaronLayton** [sampotts/plyr#2882]
The ESM entry selected by `exports.import` points to `src/js/plyr.js`, which contains extensionless relative imports (e.g. `./utils/urls`). With strict ESM resolution (e.g. Rspack/Webpack’s fully specified mode or Node ESM rules), this fails to resolve and breaks builds.

## Current behaviour

`plyr` publishes the below
```json
"exports": {
    ".": {
        "types": "./src/js/plyr.d.ts",
        "import": "./src/js/plyr.js",
        "require": "./dist/plyr.js",
        "browser": "./dist/plyr.min.js",
        "default": "./dist/plyr.js"
    },
    "./dist/plyr.css": "./dist/plyr.css",
    "./css": "./dist/plyr.css",
    "./plyr.scss": "./src/sass/plyr.scss"
},
```

The `src` uses extensionless relative imports like:

```js
import { parseUrl } from './utils/urls';
```

Modern bundlers enforcing fully specified ESM fail with:

```bash
Module not found: Can't resolve './utils/urls'
help: Did you mean './utils/urls.js'?
The request './utils/urls' failed to resolve only because it was resolved as fully specified...
```

Noted on Version: `plyr@3.8.3` at least

## Expected behaviour
* ESM consumers should be able to build without custom resolver relaxations.
* Either:
    * All relative imports in src include file extensions (e.g. ./utils/urls.js), or
    * The ESM import condition points to a compiled ESM file in dist (e.g. ./dist/plyr.esm.js) with compliant imports.

## Why it matters
Strict ESM resolution requires fully specified file extensions for relative specifiers.

Many modern toolchains (Rspack/Webpack in strict mode, Node ESM) adhere to this and fail on extensionless imports.

# Minimal repro
* Install `plyr@3.8.3`
* Use a bundler that honors fully specified ESM (e.g. Rspack/Webpack 5 defaults when type: "module").
* import 'plyr'
* Build → error as above.

## Workarounds (for consumers)
* Relax resolution for JS: resolve.fullySpecified: false for \.m?js$

Note this is not a great or longterm fix but relaxing this rule or pinning your install version to a known working one will get you past for now. For me the pinned version is currently `3.7.8`

> Note: A few other people have raised this issue so I will try and link them all together.

**Comment by sampotts** [comment]
Thanks for this. It _should_ now be resolved in 3.8.4 but let me know if not!

**Comment by limonte** [comment]
Not sure if related or now, but I'm still getting 

<img width="2248" height="396" alt="Image" src="https://github.com/user-attachments/assets/dbcbc662-08d7-4185-9a4a-c457d5ed97b5" />

**Comment by limonte** [comment]
This patch is a workaround for my case:

```diff
Index: node_modules/plyr/package.json
===================================================================
--- node_modules/plyr/package.json
+++ node_modules/plyr/package.json
@@ -29,8 +29,9 @@
       "require": "./dist/plyr.js",
       "browser": "./dist/plyr.min.js",
       "default": "./dist/plyr.js"
     },
+    "./dist/plyr.js": "./dist/plyr.js",
     "./dist/plyr.css": "./dist/plyr.css",
     "./css": "./dist/plyr.css",
     "./plyr.scss": "./src/sass/plyr.scss"
   },
```

**Comment by limonte** [comment]
I can contribute with a PR in case this project is maintained again (which it seems a little 😄)
