### ISSUE TITLE
Require Js and plyr is not working for me

### ISSUE THREAD

**Issue by premhameed** [sampotts/plyr#488]
Hi ,
It is not working for me

requirejs.config({

baseUrl: 'js',
paths: {
    'jquery':'jquery',       
    'bootstrap':'lib/bootstrap.min',
    'greensock':'lib/TweenMax.min',
    'waypoint':'lib/jquery.waypoints.min',
    'modernizr':'lib/modernizr',
    'aos':'lib/aos',
    'plyr':'lib/plyr',
    'home':'home',
    
},
shim: {
    
    'modernizr': [ "jquery" ],
    'bootstrap': ["jquery"],
    'aos': ["jquery"],
 
    
},    
});

define(['jquery','modernizr','aos','greensock','waypoint','enhance','bootstrap','plyr'], function($,modernizer,AOS) {
$(document).ready(function(){
plyr.setup();
});
});

**Comment by ckeim** [comment]
Same for me. I'm getting "Uncaught ReferenceError: plyr is not defined" - even though the plyr.min.js is being attached to the page.

**Comment by humayuncep** [comment]
jquery.min.js:2 Uncaught ReferenceError: plyr is not defined
    at HTMLDocument.<anonymous> (main.js:779)
    at l (jquery.min.js:2)
    at c (jquery.min.js:2)


I got this error in new versions. I tested for v2.0.13, there is no this kind of error. But for vimeo video, it shows the vimeo controller along with the plyr control. It's kinda weird showing both of them together
![screen shot 2018-02-19 at 12 15 12 pm](https://user-images.githubusercontent.com/11034890/36364505-9dcc1da6-156e-11e8-984c-4d163e964ffd.png)

**Comment by friday** [comment]
@humayuncep Plyr v3 is not compatible with plyr 2. Read more here if you want to test it https://github.com/sampotts/plyr/issues/766

About the vimeo video controllers showing for v2, please report that separately using the issue template.

**Comment by friday** [comment]
@premhameed: Check that you are not using v3 since `plyr.setup()` is v2 syntax. If you are, then either downgrade to v2 or update the the initialized from `plyr.setup(element, options)` to `new Plyr(element, options)`.

If there is something wrong with the module still, please try to change the `lib/plyr` reference to point directly to the dist output and report the version.

**Comment by sampotts** [comment]
I think this is fixed in v3? Feel free to re-open if that's not the case 👍

**Comment by goranhorvathr** [comment]
This is still an issue in all of v3. Im trying to debug what is going on but this issue is still here.
