### ISSUE TITLE
HLS Streaming not show poster image

### ISSUE THREAD

**Issue by dungphanxuan** [sampotts/plyr#602]
I set source for HLS Streaming. So poster image on top not showing.

![image](https://user-images.githubusercontent.com/10725732/27018257-25954af0-4f59-11e7-9e4c-3fc493d958dd.png)

**Comment by jackguoAtJogg** [comment]
Is this fixed cause I still have this issue.

**Comment by dib258** [comment]
This was corrected at some point but it seems to be broken again since tagged version 3.5.10, you can downgrade to 3.5.6 for this to work with hls.js. (I tried 3.5.9 and it was not working so I tried the version referenced [here](https://github.com/sampotts/plyr/issues/1763)).

**Comment by sampotts** [comment]
I'm going to re-instate the poster image logic for HTML5 videos. For now as above, revert to `3.5.6`.

**Comment by regiside** [comment]
Hey, Still seeing this issue on safari and mobile chrome. If I set preload="none" the poster doesn't break, otherwise it immediately get's hidden by the first frame of the HSL source. Any news on when we'll be able to upgrade past 3.5.6?

**Comment by pushkidman** [comment]
@sampotts any update on the issue? still happening for me
