### ISSUE TITLE
[dev branch] 13:36-43 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by CanRau** [sampotts/plyr#614]
- Issue does not already exist

### Expected behaviour 
no webpack warnings

### Actual behaviour
I'm getting the mentioned warning when running webpack and plyr 3.0.0 development version

### Environment

- Operating System: macOS
- Version: 10.12.5
- webpack 2.3.3

### Steps to reproduce 
- yarn add git://github.com/sampotts/plyr.git#develop
- run webpack

thanks for the great player! was easier to setup up plyr, coding a playlist than using video.js+playlist 👍 

I switched to dev to use the offline available blank.mp4 and to see if it works ;)

**Comment by sampotts** [comment]
Cool. Will take a look. BTW I'm still working on the develop branch so it will be broken.

**Comment by CanRau** [comment]
awesome and thanks in advance :D

**Comment by sampotts** [comment]
It's from here - any ideas?

https://gist.github.com/wilmoore/3880415

**Comment by CanRau** [comment]
maybe this helps https://github.com/dcodeIO/protobuf.js/issues/339 ?

changing /src/js/plyr.js L13 from
`module.exports = definition(require);`
to
`module.exports = definition();`
at least compiles properly
but of course errors will arise later like
`"TypeError: _plyr2.default.setup is not a function"`

**Comment by sampotts** [comment]
This should be resolved now

**Comment by tristantbg** [comment]
I am still having this issue, how can I fix it ?

I tried with the master and develop branch.

Thank you.
