### ISSUE TITLE
Exit fullscreen button tooltip says "Enter fullscreen" in Chrome

### ISSUE THREAD

**Issue by friday** [sampotts/plyr#881]
Using plyr 3.1.0, while in fullscreen mode, the fullscreen toggle button tooltip says "Enter fullscreen" in Chrome.

Can be replicated using the demo https://plyr.io/

Firefox is unaffected, and I haven't tried this in any other browsers.

**Comment by sampotts** [comment]
Will look at this tonight 👍 Fullscreen API is dogs breakfast across the browsers.

**Comment by friday** [comment]
Yes, It's ridiculous. I'm using a third party library "screenful" only to avoid handling this myself.

**Comment by sampotts** [comment]
Hey @friday, this should be resolved now. Feel free to re-open if not...

**Comment by friday** [comment]
It's still happening I'm afraid (can be replicated at https://plyr.io/)

I can't reopen though.

**Comment by sampotts** [comment]
Hmm, on Chrome 66 I don't get it ... 

![image](https://user-images.githubusercontent.com/719092/38876456-d8ce064a-429f-11e8-9e39-0f5809dad789.png)

**Comment by sampotts** [comment]
Chrome 65 windows... 

![image](https://user-images.githubusercontent.com/719092/38876541-fe877128-429f-11e8-9d29-9e29d81b29bc.png)

**Comment by friday** [comment]
That's really strange. I'm using Chrome v65.0.3325.181 on os x El capitan, and have force-reloaded Plyr (disabling cache).

![screen shot 2018-04-17 at 16 34 46](https://user-images.githubusercontent.com/515120/38876949-d9c09410-425d-11e8-869b-6ab85d6e1716.png)

**Comment by sampotts** [comment]
Ah damn, I don't have El Capitan any more. Literally upgraded the only machine I had running it. I'll see if I can find another way to test. Should setup a VM I guess. 

It must be something to do with the event as that sets the pressed state of the toggle button.

**Comment by friday** [comment]
I can probably look at it though. If I'm in a minority of users getting this it shouldn't be critical (even more so at these tooltips are disabled by default).

I'm stuck since I have customized my keyboard conf and Sierra broke support for the app, so you have a free tester for El Capitan ;)

If I change `aria-pressed` to `true` it works btw, but I guess you figured that wasn't the problem.

**Comment by sampotts** [comment]
Ahh Karabiner? I saw they'd changed it to Karabiner Elements that was a little odd... I use it to customize home and end keys to act like a PC. 

The event should trigger that aria state change which effects the UI. Something must be going wrong with that.

**Comment by friday** [comment]
Karabiner indeed! I have a complete custom layout (general letter key layout, special chars, combinations, dual role keys, etc). It started off as this "I like vim, but I want to tweak it some, and be able to use the layout everywhere"-idea but It's hard to justify the time I spent on tweaking it, learning it or things like this. I know about Karabiner Elements, but haven't been able to use it. 

Seems like I've missed out on some updates recently though, so hopefully I'm wrong and can actually make the switch.
